# Generated by Django 2.2.9 on 2023-04-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0004_auto_20230407_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='image',
            field=models.ImageField(blank=True, upload_to='discussions/', verbose_name='Image'),
        ),
    ]
